
project_id = "migsumagxwcavneegjtz"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true

[auth.email]
enabled = true

[realtime]
enabled = true

[functions.hubspot-auth]
verify_jwt = false
